=== savioa/novocantico/xml/xsd/hino.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
    xmlns="http://www.novocantico.com.br/schema/hino"
    targetNamespace="http://www.novocantico.com.br/schema/hino"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified"
    attributeFormDefault="unqualified">
    <xs:include schemaLocation="assunto.xsd" />
    <xs:include schemaLocation="metrica.xsd" />
    <xs:include schemaLocation="origem.xsd" />
    <xs:include schemaLocation="referencia_biblica.xsd" />
    <xs:element name="hino">
        <xs:annotation>
            <xs:documentation>Hino</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tit_ori" maxOccurs="unbounded" minOccurs="0" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>Título original</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="pri_ver_ori" maxOccurs="unbounded" minOccurs="0" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>Primeiro verso original</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="ori_let" maxOccurs="unbounded" minOccurs="0" type="TS_origem">
                    <xs:annotation>
                        <xs:documentation>Origem da letra</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="ori_mus" maxOccurs="unbounded" minOccurs="0" type="TS_origem">
                    <xs:annotation>
                        <xs:documentation>Origem da música</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="ref_bib" maxOccurs="unbounded" minOccurs="0" type="TS_referencia_biblica" />
                <xs:element name="tex">
                    <xs:annotation>
                        <xs:documentation>Texto</xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="est" maxOccurs="unbounded">
                                <xs:annotation>
                                    <xs:documentation>Estrofe</xs:documentation>
                                </xs:annotation>
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ver" maxOccurs="unbounded" type="TS_verso" />
                                        <xs:element name="cor" minOccurs="0" maxOccurs="unbounded">
                                            <xs:annotation>
                                                <xs:documentation>Coro</xs:documentation>
                                            </xs:annotation>
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="ver" maxOccurs="unbounded" type="TS_verso" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="num" use="required">
                <xs:annotation>
                    <xs:documentation>Número</xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[0-9][0-9][0-9][A-Z]?|[A-Z]" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="tit" type="xs:string" use="required">
                <xs:annotation>
                    <xs:documentation>Título</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="sec" type="TS_secao" use="required" />
            <xs:attribute name="ass" type="TS_assunto" use="required" />
            <xs:attribute name="met" type="TS_metrica" use="required" />
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TS_verso">
        <xs:annotation>
            <xs:documentation>Verso</xs:documentation>
        </xs:annotation>
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="voz" type="xs:string" use="optional">
                    <xs:annotation>
                        <xs:documentation>Voz</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== savioa/novocantico/xml/058.xml
<?xml version="1.0" encoding="utf-8"?>
<hino xsi:schemaLocation="http://www.novocantico.com.br/schema/hino xsd/hino.xsd" sit="sem_audio" num="58" tit="Ofertas" sec="01_Louvor_e_Adoração" ass="01_11_Gratidão" met="8_6_8_6" xmlns="http://www.novocantico.com.br/schema/hino" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <tit_ori>Ofertas</tit_ori>
    <ori_let id="GueirosJ" />
    <ori_mus id="WilsonH" />
    <ref_bib liv="Sl" cap="65" ver="11,12" />
    <tex>
        <est>
            <ver>A minha vida, com seus bens,</ver>
            <ver>Provém de ti, Senhor.</ver>
            <ver>Saúde, veste, abrigo e pão</ver>
            <ver>São dons do teu amor!</ver>
        </est>
        <est>
            <ver>Oh! Não permitas, Pai de amor</ver>
            <ver>Que aquilo que me dás</ver>
            <ver>Eu ouse, incauto, desviar</ver>
            <ver>Em causas vãs ou más!</ver>
        </est>
        <est>
            <ver>Não deixes que meu coração</ver>
            <ver>Se engolfe no prazer,</ver>
            <ver>E no fruir de muitos dons</ver>
            <ver>Eu venha a te esquecer!</ver>
        </est>
        <est>
            <ver>Mordomo teu, eu quero dar</ver>
            <ver>À Igreja, em proporção</ver>
            <ver>A quantas bênçãos recebi</ver>
            <ver>De tuas próprias mãos!</ver>
        </est>
        <est>
            <ver>Aceita a minha oferta, ó Deus,</ver>
            <ver>E bênçãos dá-me a flux.</ver>
            <ver>Sim, dá-me sempre o que ofertar</ver>
            <ver>À causa de Jesus!</ver>
            <ver>Amém.</ver>
        </est>
    </tex>
</hino>

=== savioa/novocantico/xml/067.xml
<?xml version="1.0" encoding="UTF-8"?>
<hino
    num="67"
    tit="Coração quebrantado"
    sec="02_Confissão" ass="02_01_Contrição_e_Arrependimento"
    met="10_10_10_10"
    xsi:schemaLocation="http://www.novocantico.com.br/schema/hino xsd/hino.xsd"
    xmlns="http://www.novocantico.com.br/schema/hino"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <tit_ori>Cleanse me</tit_ori>
    <pri_ver_ori>Cleanse me</pri_ver_ori>
    <ori_let id="OrrJE" />
    <ori_let id="KaschelW" />
    <ori_mus id="MelodiaMaori" />
    <ref_bib liv="Sl" cap="139" ver="23,24" />
    <tex>
        <est>
            <ver>Sonda-me, ó Deus, pois vês meu coração!</ver>
            <ver>Prova-me, ó Pai, te peço em oração.</ver>
            <ver>De todo o mal liberta-me, Senhor,</ver>
            <ver>Até da transgressão que oculta for.</ver>
        </est>
        <est>
            <ver>Vem me lavar dos vis pecados meus,</ver>
            <ver>Conforme prometeste, meu bom Deus.</ver>
            <ver>Faze-me arder e consumir de amor,</ver>
            <ver>Pois quero te magnificar, Senhor.</ver>
        </est>
        <est>
            <ver>Todo o meu ser não considero meu;</ver>
            <ver>Quero gastá-lo no serviço teu.</ver>
            <ver>Minhas paixões tu podes dominar,</ver>
            <ver>Pois tu, Senhor, vieste em mim morar.</ver>
        </est>
        <est>
            <ver>Lá do alto céu o avivamento vem</ver>
            <ver>E que comece em mim, seguindo além.</ver>
            <ver>O teu poder, as bênçãos, teu favor</ver>
            <ver>Concede aos que são teus, ó Pai de amor.</ver>
            <ver>Amém.</ver>
        </est>
    </tex>
</hino>

=== savioa/novocantico/xml/007.xml
<?xml version="1.0" encoding="UTF-8"?>
<hino sit="sem_audio"
    xmlns="http://www.novocantico.com.br/schema/hino"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.novocantico.com.br/schema/hino xsd/hino.xsd"
    num="007"
    tit="Glória à Trindade"
    sec="01_Louvor_e_Adoração"
    ass="01_02_Deus_Trino"
    met="6_6_4_6_6_6_4">
    <tit_ori>Greenwood</tit_ori>
    <ori_let id="GueirosJ" />
    <ori_mus id="ProutE" />
    <ref_bib liv="Sl" cap="9" ver="1" />
    <ref_bib liv="Sl" cap="29" ver="1,2" />
    <tex>
        <est>
            <ver>A ti, meu Criador,</ver>
            <ver>Dos altos céus Senhor,</ver>
            <ver>Eu quero honrar.</ver>
            <ver>Aceita a adoração</ver>
            <ver>Que a voz e o coração</ver>
            <ver>Te vêm, bondoso Pai,</ver>
            <ver>Aqui prestar.</ver>
        </est>
        <est>
            <ver>A ti, Emanuel,</ver>
            <ver>Por teu amor fiel</ver>
            <ver>Rendo eu louvor.</ver>
            <ver>Do céu trouxeste a luz,</ver>
            <ver>Por mim sofreste a cruz,</ver>
            <ver>Bendito sejas, pois,</ver>
            <ver>Meu Redentor</ver>
        </est>
        <est>
            <ver>A ti, Consolador,</ver>
            <ver>Divino Preceptor,</ver>
            <ver>Eu louvarei.</ver>
            <ver>Com teu poder sem par,</ver>
            <ver>Oh! Vem me iluminar,</ver>
            <ver>E assim, ao teu fulgor,</ver>
            <ver>Eu brilharei.</ver>
            <ver>Amém.</ver>
        </est>
    </tex>
</hino>

=== savioa/novocantico/xml/003.xml
<?xml version="1.0" encoding="UTF-8"?>
<hino
    xmlns="http://www.novocantico.com.br/schema/hino"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.novocantico.com.br/schema/hino xsd/hino.xsd"
    num="003"
    tit="A Igreja em Adoração"
    tit_ant="Teu Povo Congregado"
    sec="01_Louvor_e_Adoração"
    ass="01_02_Deus_Trino"
    met="11_10_11_10_D">
    <tit_ori>O selig Haus</tit_ori>
    <ori_let id="KalleySP" ano="1872" />
    <ori_mus id="NiemeyerE" ano="1854" />
    <ref_bib liv="Dt" cap="33" ver="3" />
    <ref_bib liv="Lc" cap="10" ver="39" />
    <tex>
        <est>
            <ver>Eterno Pai, teu povo congregado,</ver>
            <ver>Humilde entoa o teu louvor aqui!</ver>
            <ver>No dia para o culto reservado,</ver>
            <ver>Com esperança olhamos para ti.</ver>
            <ver>Teu santo livro, ó grande Deus, tomamos</ver>
            <ver>Com fé singela e reverente amor;</ver>
            <ver>E, como atentos filhos, procuramos</ver>
            <ver>Ciência na Palavra do Senhor.</ver>
        </est>
        <est>
            <ver>Jesus! Aos teus benditos pés sentados</ver>
            <ver>Queremos teu conselho receber,</ver>
            <ver>E sendo por ti mesmo doutrinados,</ver>
            <ver>De mais em mais na santa fé crescer.</ver>
            <ver>Do mundo e seus encargos retirados</ver>
            <ver>Queremos descansar em ti, Senhor,</ver>
            <ver>Mirando os ricos bens entesourados</ver>
            <ver>Na plenitude do teu vasto amor.</ver>
        </est>
        <est>
            <ver>Ensina aos teus, Espírito divino,</ver>
            <ver>Dissipa as trevas destes corações;</ver>
            <ver>E com a luz do teu celeste ensino,</ver>
            <ver>Vem aclarar as santas instruções.</ver>
            <ver>Aviva em nós as forças da memória,</ver>
            <ver>Pois sempre mais queremos conhecer</ver>
            <ver>O Rei dos céus, o Cristo cuja glória</ver>
            <ver>Enleva os santos anjos de prazer. Amém.</ver>
        </est>
    </tex>
</hino>

=== savioa/novocantico/xml/068.xml
<?xml version="1.0" encoding="UTF-8"?>
<hino
    num="68"
    tit="Necessidade"
    sec="02_Confissão" ass="02_01_Contrição_e_Arrependimento"
    met="12_11_12_11"
    xsi:schemaLocation="http://www.novocantico.com.br/schema/hino xsd/hino.xsd"
    xmlns="http://www.novocantico.com.br/schema/hino"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <tit_ori>Telford</tit_ori>
    <tit_ant>Senhor, eu preciso de Ti</tit_ant>
    <tit_ant>Dependência de Deus</tit_ant>
    <ori_let id="GoncalvesAC" ano="1952" />
    <ori_mus id="BragaHRF" ano="1952" />
    <ref_bib liv="Sl" cap="34" ver="10" />
    <tex>
        <est>
            <ver>Eu creio, Senhor, na divina promessa,</ver>
            <ver>Vitórias já tive nas lutas aqui.</ver>
            <ver>Contudo, é mui certo que a gente tropeça;</ver>
            <ver>Por isso, Senhor, eu preciso de ti.</ver>
        </est>
        <est>
            <ver>A luz que me guia no escuro caminho</ver>
            <ver>Fulgura de cima, do Sol criador;</ver>
            <ver>Contudo, não posso segui-la sozinho;</ver>
            <ver>Por isso eu preciso de ti, meu Senhor.</ver>
        </est>
        <est>
            <ver>Bem sei que nas preces eu posso buscar-te,</ver>
            <ver>Jamais dessa bênção na vida eu descri;</ver>
            <ver>Contudo, é possível que dela me afaste;</ver>
            <ver>Por isso, Senhor, eu preciso de ti.</ver>
        </est>
        <est>
            <ver>Esforços da terra, precário destino,</ver>
            <ver>Empenho dos homens, riqueza, o que for,</ver>
            <ver>Não valem a bênção do reino divino;</ver>
            <ver>Por isso eu preciso de ti, meu Senhor.</ver>
            <ver>Amém.</ver>
        </est>
    </tex>
</hino>

=== savioa/novocantico/xml/062.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../hino.xsl"?>
<hino
    num="62"
    tit="Hino de Gratidão"
    sec="01_Louvor_e_Adoração" ass="01_11_Gratidão"
    met="11_11_11_11_Coro"
    xsi:schemaLocation="http://www.novocantico.com.br/schema/hino xsd/hino.xsd"
    xmlns="http://www.novocantico.com.br/schema/hino"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <tit_ori>Hino de Gratidão</tit_ori>
    <ori_let id="OliveiraJC" />
    <ori_mus id="NogueiraE" />
    <ori_mus id="ManuelRE" ano="1975" />
    <ref_bib liv="Sl" cap="103" ver="1,2" />
    <ref_bib liv="2Co" cap="9" ver="15" />
    <tex>
        <est>
            <ver>Graças te dou por tudo que me deste,</ver>
            <ver>Primeiro a salvação em meu Jesus.</ver>
            <ver>Graças te dou por tudo que fizeste</ver>
            <ver>Por este pecador salvo na cruz!</ver>
            <cor>
                <ver>Graças, graças, mil graças</ver>
                <ver>A ti, meu Salvador!</ver>
                <ver>Graças, graças, mil graças</ver>
                <ver>Por teu precioso amor!</ver>
            </cor>
        </est>
        <est>
            <ver>Eu te agradeço a bênção do trabalho</ver>
            <ver>E do meu lar, que alegra o meu viver;</ver>
            <ver>A correção paterna, quando falho,</ver>
            <ver>Provando o teu amor pelo meu ser.</ver>
        </est>
        <est>
            <ver>Eu te agradeço o pão de cada dia,</ver>
            <ver>A água que alivia a sede dura</ver>
            <ver>E o sol que aquece a pobre gente fria:</ver>
            <ver>São bênçãos que enchem a terra de fartura.</ver>
        </est>
        <est>
            <ver>Eu te agradeço, ó Pai, os meus amigos,</ver>
            <ver>E os inimigos também te agradeço.</ver>
            <ver>Sou grato por vitórias em perigos</ver>
            <ver>E outras bênçãos que eu não mereço.</ver>
            <ver>Amém.</ver>
        </est>
    </tex>
</hino>

=== savioa/novocantico/xml/038.xml
<?xml version="1.0" encoding="utf-8"?>
<hino xsi:schemaLocation="http://www.novocantico.com.br/schema/hino xsd/hino.xsd" num="38" tit="Louvores sem Fim" tit_ant="Mil Vezes Mil Louvores" sec="01_Louvor_e_Adoração" ass="01_09_Deus_Salvador" met="13_13_13_13_Coro" xmlns="http://www.novocantico.com.br/schema/hino" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <tit_ori>Salomão</tit_ori>
    <ori_let id="WrightHM" ano="1901" />
    <ori_mus id="KirkpatrickWJ" />
    <ref_bib liv="Ap" cap="7" ver="9,10" />
    <tex>
        <est>
            <ver>Mil vezes mil louvores rendamos a Jesus</ver>
            <ver>Que, da mais alta glória, desceu até à cruz!</ver>
            <ver>Por sua imensa graça, por seu insigne amor,</ver>
            <ver>Por todos seja sempre louvado o Salvador.</ver>
            <cor>
                <ver>Mil vezes, sim, mil vezes, sim,</ver>
                <ver>Louvores ao Senhor</ver>
                <ver>Que nos amou e nos salvou,</ver>
                <ver>Bendito Salvador!</ver>
            </cor>
        </est>
        <est>
            <ver>Eis ao redor do trono do Redentor Jesus,</ver>
            <ver>Milhares de milhares em refulgente luz!</ver>
            <ver>Com reverência adoram o grande Salvador,</ver>
            <ver>E ao bom Cordeiro rendem a honra e o louvor.</ver>
        </est>
        <est>
            <ver>Oh! Vinde agora, todos, também a celebrar</ver>
            <ver>As glórias sempiternas do Redentor sem par!</ver>
            <ver>Com vozes de vitória seu Nome proclamai!</ver>
            <ver>Mil vezes mil louvores a Cristo tributai!</ver>
        </est>
    </tex>
</hino>

=== savioa/novocantico/xml/063.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../hino.xsl"?>
<hino
    num="63"
    tit="As muitas bênçãos"
    sec="01_Louvor_e_Adoração" ass="01_11_Gratidão"
    met="11_11_11_11_Coro"
    xsi:schemaLocation="http://www.novocantico.com.br/schema/hino xsd/hino.xsd"
    xmlns="http://www.novocantico.com.br/schema/hino"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <tit_ori>Count your blessings</tit_ori>
    <tit_ant>Conta as muitas bênçãos</tit_ant>
    <pri_ver_ori>When upon life's billows you are tempest tossed</pri_ver_ori>
    <ori_let id="OatmanJrJ" />
    <ori_mus id="SmartER" ano="1903" />
    <ori_mus id="ExcellEO" />
    <ref_bib liv="Sl" cap="103" ver="1,2" />
    <tex>
        <est>
            <ver>Se da vida as vagas procelosas são,</ver>
            <ver>Se, com desalento, julgas tudo vão,</ver>
            <ver>Conta as muitas bênçãos, dize-as de uma vez,</ver>
            <ver>E verás, surpreso, quanto Deus já fez.</ver>
            <cor>
                <ver>Conta as bênçãos, dize quantas são,</ver>
                <ver>Recebidas da divina mão!</ver>
                <ver>Vem dizê-las, todas de uma vez,</ver>
                <ver>E verás, surpreso, quanto Deus já fez!</ver>
            </cor>
        </est>
        <est>
            <ver>Tens acaso mágoas, triste é teu lidar?</ver>
            <ver>É a cruz pesada que tens de levar?</ver>
            <ver>Conta as muitas bênçãos! Logo exultarás</ver>
            <ver>E, fortalecido, tudo vencerás!</ver>
        </est>
        <est>
            <ver>Quando vires outros com seu ouro e bens,</ver>
            <ver>Lembra que tesouros prometidos tens.</ver>
            <ver>Nunca os bens da terra poderão comprar</ver>
            <ver>A mansão celeste que vais habitar.</ver>
        </est>
        <est>
            <ver>Seja o teu combate longo ou breve aqui,</ver>
            <ver>Não te desanimes: Deus será por ti!</ver>
            <ver>Seu divino auxílio, minorando o mal,</ver>
            <ver>Te dará consolo e galardão final.</ver>
        </est>
    </tex>
</hino>
